# Generated by Django 5.2.6 on 2025-11-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/'),
        ),
    ]
