# Generated by Django 5.2.6 on 2025-11-29 18:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_page_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
