"""
Django settings for remedial_system project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dqb-=h033xz)mdu)r^hvd-gsg7d@4qbqly&s@w6m7)^ok-rc)2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = [
    'lukore.pythonanywhere.com',
    'localhost',
    '127.0.0.1',
    '192.168.8.100',
    '192.168.8.192'
]


# Application definition

INSTALLED_APPS = [
   'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # our custom app
    'lessons',

    # public website app
    'website',

    # rich text editor
    'ckeditor',
    'ckeditor_uploader',
    # Library app
    'library',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'remedial_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'remedial_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Web Push (VAPID) configuration for teacher browser notifications.
# Keys generated by generate_vapid_keys.py.
WEBPUSH_VAPID_PUBLIC_KEY = "BMr8TkpqAqzTrzoq5jF0byTmikx6c4HQX6PLEKXs3klz14tB9sWpQm3u7B9U1zjTWLMw6GQyIWOJ57doLsCIO5c"
WEBPUSH_VAPID_PRIVATE_KEY = "q-lql28IrOeCKkzA_xcsmYQrC5DgODyGkFc-1fT_6zY"
WEBPUSH_VAPID_CLAIMS = {
    "sub": "mailto:admin@example.com",
}

# Redirect to login page if user is not authenticated
LOGIN_URL = '/accounts/login/'

# Redirect after successful login
LOGIN_REDIRECT_URL = '/lessons/teacher/dashboard/'

# Redirect after logout
LOGOUT_REDIRECT_URL = '/accounts/login/'
# settings.py




DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = BASE_DIR / "staticfiles"

# CKEditor uploaded files folder (inside MEDIA_ROOT)
CKEDITOR_UPLOAD_PATH = "ckeditor/"

# CKEditor rich text configuration
CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": "Full",
        "height": 300,
        "width": "100%",
        # Allow basic formatting, lists, links, tables, images, etc.
        "toolbar_Full": [
            ["Format", "Styles"],
            ["Bold", "Italic", "Underline", "Strike", "Subscript", "Superscript", "RemoveFormat"],
            ["NumberedList", "BulletedList", "Outdent", "Indent", "Blockquote"],
            ["JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock"],
            ["Link", "Unlink", "Anchor"],
            ["Image", "Table", "HorizontalRule", "SpecialChar"],
            ["TextColor", "BGColor"],
            ["Undo", "Redo"],
            ["Maximize", "Source"],
        ],
        # Custom styles, including a simple "Info box" text box
        "stylesSet": [
            {
                "name": "Info box",
                "element": "p",
                "attributes": {"class": "info-box"},
            },
        ],
    }
}
