# Generated by Django 5.2.7 on 2025-11-06 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normallessonattendance',
            options={'verbose_name': 'Lesson attendance', 'verbose_name_plural': 'Lesson attendances'},
        ),
        migrations.AlterModelOptions(
            name='normallessonslot',
            options={'verbose_name': 'Lesson slot', 'verbose_name_plural': 'Lesson slots'},
        ),
    ]
