# Generated by Django 5.2.6 on 2025-12-20 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_teacherpushsubscription_sentclassnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentRemedialNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_remedial_notifications', to='lessons.timetable')),
            ],
            options={
                'unique_together': {('timetable', 'date', 'start_time')},
            },
        ),
    ]
