# Generated by Django 5.2.6 on 2025-12-23 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_lessonrecord_teacher_alter_timetable_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='JointClassGroupSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('class_groups', models.ManyToManyField(blank=True, to='lessons.classgroup')),
            ],
        ),
        migrations.CreateModel(
            name='JointSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lessons.subject')),
            ],
        ),
    ]
