# Generated by Django 5.2.6 on 2026-09-01 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_jointclassgroupset_jointsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 2025-2026', max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False, help_text='The currently active academic year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='classgroup',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this class group', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='lessons.academicyear'),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year when payment was made', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_payments', to='lessons.academicyear'),
        ),
        migrations.AddField(
            model_name='week',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this week', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='lessons.academicyear'),
        ),
    ]
