# Generated by Django 5.2.6 on 2026-09-01 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_academicyear_classgroup_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='end_date',
            field=models.DateField(help_text='End date of this week'),
        ),
        migrations.AlterField(
            model_name='week',
            name='number',
            field=models.PositiveIntegerField(help_text='Week number (e.g., 1, 2, 3...)'),
        ),
        migrations.AlterField(
            model_name='week',
            name='start_date',
            field=models.DateField(help_text='Start date of this week'),
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Term 1, Term 2, Term 3', max_length=50)),
                ('start_date', models.DateField(help_text='Start date of this term')),
                ('end_date', models.DateField(help_text='End date of this term')),
                ('is_active', models.BooleanField(default=False, help_text='The currently active term')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(help_text='Academic year for this term', on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='lessons.academicyear')),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
                'ordering': ['start_date'],
                'unique_together': {('name', 'academic_year')},
            },
        ),
        migrations.AddField(
            model_name='week',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Term for this week', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='lessons.term'),
        ),
    ]
