# Generated by Django 5.2.6 on 2026-09-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_alter_week_end_date_alter_week_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='is_skipped',
            field=models.BooleanField(default=False, help_text='Mark if this term was skipped during setup'),
        ),
    ]
