# Generated by Django 5.2.6 on 2026-09-01 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_term_is_skipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='normallessonslot',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this lesson slot', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normal_slots', to='lessons.academicyear'),
        ),
        migrations.AddField(
            model_name='normallessonslot',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Term for this lesson slot', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normal_slots', to='lessons.term'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this timetable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='lessons.academicyear'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Term for this timetable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='lessons.term'),
        ),
    ]
