# Generated by Django 5.2.6 on 2026-09-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_normallessonslot_academic_year_normallessonslot_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='is_wrapped',
            field=models.BooleanField(default=False, help_text='Mark if this term has been wrapped/completed'),
        ),
    ]
