# Generated by Django 5.2.6 on 2026-09-01 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_term_is_wrapped'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Current term for this student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='lessons.term'),
        ),
    ]
