# Generated by Django 5.2.6 on 2026-09-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_student_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPreviousBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_carried_forward', models.BooleanField(default=False, help_text='Whether this balance was automatically carried forward from previous year')),
                ('notes', models.TextField(blank=True, help_text='Notes about this previous balance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_balances', to='lessons.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_balances', to='lessons.student')),
            ],
        ),
    ]
