# Generated by Django 5.2.6 on 2026-09-02 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0017_studentpreviousbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Technical Subjects', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(blank=True, help_text='Optional: restrict to specific academic year', null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.academicyear')),
                ('class_groups', models.ManyToManyField(blank=True, help_text='Optional: restrict to specific classes', to='lessons.classgroup')),
                ('subjects', models.ManyToManyField(help_text='Subjects that run together', to='lessons.subject')),
            ],
        ),
    ]
