# Generated by Django 5.2.6 on 2026-09-02 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0018_subjectgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectgroup',
            name='class_groups',
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='joint_class_group',
            field=models.ForeignKey(blank=True, help_text='Optional: restrict to specific joint class group', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.jointclassgroupset'),
        ),
    ]
